/**
 * Portfolio content manifest.
 *
 * This is an allowlist, not a denylist: only repositories listed here are shown.
 * Anything not listed stays off the site, so an empty or abandoned repo can
 * never leak onto the page just because it exists on GitHub.
 *
 * Everything here is checked against the repository it describes. Live numbers
 * (stars, last push, satellite counts, vote totals) are never written down —
 * app.js fetches them at load time from the sources named in LIVE_FEEDS.
 */

const PORTFOLIO_DATA = {
  developer: {
    name: "Adam Freeman",
    handle: "bitterbuick",
    tagline: "Public-data tools that keep themselves up to date.",
    github: "https://github.com/bitterbuick",
    email: "adam.w.freeman@gmail.com"
  },

  /**
   * Data published by the projects themselves, read straight from the repos.
   * Both files are regenerated by scheduled GitHub Actions workflows, so the
   * figures on this page are whatever the projects last computed.
   */
  liveFeeds: {
    starlink: "https://raw.githubusercontent.com/bitterbuick/starlink-watch/main/data/metrics.json",
    repTracker: "https://raw.githubusercontent.com/bitterbuick/rep-tracker/main/data/salinas_votes.json"
  },

  projects: [
    {
      id: "rep-tracker",
      title: "rep-tracker",
      category: "live",
      tag: "Live dashboard",
      blurb: "Every House roll-call vote cast by Rep. Andrea Salinas (D-OR-6), parsed straight from the Clerk of the House's official EVS XML feed and served as an interactive dashboard.",
      detail: "ProPublica's Congress API was retired, so this scripts directly against clerk.house.gov/evs — the primary source ProPublica itself ingested. No API key, no third-party dependency. A GitHub Actions workflow refetches new roll calls twice daily, re-scores them against an editable risk rubric, and redeploys the dashboard.",
      tech: ["Python (stdlib only)", "GitHub Actions", "GitHub Pages"],
      githubUrl: "https://github.com/bitterbuick/rep-tracker",
      liveUrl: "https://bitterbuick.github.io/rep-tracker/",
      embed: true,
      embedNote: "Filter by year, vote, or party alignment — every chart and list re-renders against the same slice.",
      run: [
        "git clone https://github.com/bitterbuick/rep-tracker && cd rep-tracker",
        "python3 scripts/fetch_votes.py   # incremental; --full refetches everything",
        "python3 scripts/score_risk.py"
      ]
    },
    {
      id: "starlink-watch",
      title: "starlink-watch",
      category: "live",
      tag: "Live dashboard",
      blurb: "Tracks the Starlink constellation's growth and the mass it will eventually deposit in the stratosphere, from CelesTrak orbital elements and confirmed decay records.",
      detail: "Satellites live about five years, then deorbit and burn up. Re-entry converts their aluminium into alumina nanoparticles that settle into the ozone layer. The four charts follow that mass through the pipeline: active satellites, on-orbit mass, re-entered mass, and an upper-bound alumina estimate. Charts are hand-rolled SVG — no charting library. Classification of the news digest is deterministic keyword scoring, not an LLM.",
      tech: ["Python", "CelesTrak", "GitHub Actions", "GitHub Pages"],
      githubUrl: "https://github.com/bitterbuick/starlink-watch",
      liveUrl: "https://bitterbuick.github.io/starlink-watch/",
      embed: true,
      embedNote: "Charts support hover tooltips, range filters, and client-side trend projection.",
      run: [
        "git clone https://github.com/bitterbuick/starlink-watch && cd starlink-watch",
        "pip install -r requirements.txt",
        "python scripts/compute_starlink_metrics.py && python scripts/build_site.py",
        "python -m unittest discover tests"
      ]
    },
    {
      id: "openai-data-explorer",
      title: "openai-data-explorer",
      category: "data",
      tag: "Local web app",
      blurb: "Ingests an OpenAI/ChatGPT privacy export ZIP and makes it searchable offline — full-text search, conversation threads, usage charts, and a PII scanner.",
      detail: "Runs entirely on your own machine against your own export; nothing is uploaded anywhere. That is also why there is no hosted demo of it — a live version would need someone's private conversation history to be meaningful. Clone it, point it at your own export, and it works.",
      tech: ["Python", "FastAPI", "SQLite FTS5", "htmx"],
      githubUrl: "https://github.com/bitterbuick/openai-data-explorer",
      run: [
        "git clone https://github.com/bitterbuick/openai-data-explorer && cd openai-data-explorer",
        "pip install -r requirements.txt",
        "python app.py   # then open http://localhost:8000"
      ],
      verified: "53 tests passing"
    },
    {
      id: "edgar-50-percent",
      title: "edgar-50-percent",
      category: "data",
      tag: "CLI",
      blurb: "Finds the majority-owned (>=50%) subsidiaries of a public company by downloading and parsing the Exhibit 21 schedule from its SEC 10-K filings.",
      detail: "Runs on SEC EDGAR's free public infrastructure — no paid API, no account, no key. The SEC only asks for a descriptive User-Agent identifying you, per their fair-access policy. Give it a ticker or a CIK and it writes a CSV.",
      tech: ["Python", "edgartools", "SEC EDGAR"],
      githubUrl: "https://github.com/bitterbuick/edgar-50-percent",
      run: [
        "git clone https://github.com/bitterbuick/edgar-50-percent && cd edgar-50-percent",
        "pip install -r requirements.txt",
        "python main.py AAPL --user-agent 'Your Name you@example.com'"
      ]
    },
    {
      id: "osintinel",
      title: "osintinel",
      category: "tools",
      tag: "CLI",
      blurb: "A small OSINT reconnaissance CLI: DNS resolution, IP geolocation, WHOIS, email scraping, and public GitHub profile lookup, one subcommand each.",
      detail: "Spiderfoot-inspired but deliberately minimal. The DNS, geolocation, email and GitHub commands need no credentials or API keys at all. The Twitter, LinkedIn and Tor commands each need their own optional package and, where relevant, credentials in a .env file — the CLI runs without them and tells you what to install.",
      tech: ["Python", "requests", "Apache-2.0"],
      githubUrl: "https://github.com/bitterbuick/osintinel",
      run: [
        "git clone https://github.com/bitterbuick/osintinel && cd osintinel",
        "pip install -r requirements.txt",
        "python src/cli/cli.py dns example.com",
        "python src/cli/cli.py github octocat --repos"
      ]
    },
    {
      id: "claude-google-drive-mcp",
      title: "claude-google-drive-mcp",
      category: "tools",
      tag: "MCP server",
      blurb: "A Model Context Protocol server that gives an LLM assistant tool access to Google Drive — searching files and reading document text — with self-hosted OAuth.",
      detail: "You hold your own OAuth credentials and tokens; nothing is brokered through a third party. Ships a debug-oauth helper for working through the consent flow before wiring it into a client.",
      tech: ["TypeScript", "Node.js", "MCP SDK", "Google Drive API"],
      githubUrl: "https://github.com/bitterbuick/claude-google-drive-mcp",
      run: [
        "git clone https://github.com/bitterbuick/claude-google-drive-mcp && cd claude-google-drive-mcp",
        "npm install && npm run build",
        "cp .env.template .env   # add your Google OAuth credentials",
        "npm run debug:oauth"
      ]
    },
    {
      id: "BallBustr",
      title: "BallBustr",
      category: "fun",
      tag: "Desktop game",
      blurb: "A brick-breaker game written with Python's built-in turtle module — paddle control, collision physics, and a fixed 60 FPS loop, in one file with no dependencies.",
      detail: "Genuinely nothing to install beyond Python itself; turtle ships with the standard library. It opens a desktop window, so there is no browser version — but it is a single file you can read top to bottom and run in one command.",
      tech: ["Python", "turtle (stdlib)", "No dependencies"],
      githubUrl: "https://github.com/bitterbuick/BallBustr",
      run: [
        "git clone https://github.com/bitterbuick/BallBustr && cd BallBustr",
        "python3 PyrickBreack.py   # arrow keys move the paddle"
      ]
    }
  ],

  /**
   * Filter tabs. Counts are computed from the projects above at render time.
   */
  filters: [
    { id: "all", label: "Everything" },
    { id: "live", label: "Live dashboards" },
    { id: "data", label: "Data & analysis" },
    { id: "tools", label: "CLI & servers" },
    { id: "fun", label: "For fun" }
  ]
};
